In [ ]:
# Source: https://codesolid.com/numpy-practice-questions-to-make-you-an-expert/

In [1]:
# E01

# Using a NumPy function, how would you create a one-dimensional NumPy array of the numbers from 10 to 100,
# counting by 10?

import numpy as np

array = np.arange(10, 101, 10)
array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [2]:
# E02

# How could you create the same NumPy array using a Python range and a list?

import numpy as np

array = np.array(list(range(10, 101, 10)))

array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [3]:
# E03

# What happens if you pass no arguments to the np.array()?

# Answer: It returns an error, since np.array requires an object as parameter

array = np.array()
array

TypeError: array() missing required argument 'object' (pos 0)

In [4]:
# E04

# How might you create a NumPy array of the capital letters, A-Z?

import numpy as np

lista = []
for i in range(65, 91):   #91 == 65 + 26. 65 é o ASCII da letra A, e +26 é pra percorrer todas as maiúsculas até o Z
    lista.append(chr(i))
    
array = np.array(lista)
array

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype='<U1')

In [ ]:
# E05

# How would you create a ten-element NumPy array object of all zeros?

import numpy as np

array = np.zeros(10)
array

In [6]:
# E06

# How would you find the data type given in #4.

# E07

#What is the data type for #4?

import numpy as np

### REPETINDO A 4 ###
lista = []
for i in range(65, 91):   #91 == 65 + 26. 65 é o ASCII da letra A, e +26 é pra percorrer todas as maiúsculas até o Z
    lista.append(chr(i))
    
array = np.array(lista)
array
#####################

array.dtype

dtype('<U1')

In [1]:
# E08

# What function would return the same number of elements, but of all ones?

import numpy as np

array = np.ones(10)
array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# E09

# How could you create a ten-element array of random integers between 1 and 5 (inclusive)?

# Numpy has a 'random' module, which has a 'randint' function:

import numpy as np

array = np.random.randint(1, 6, size = 10)
array

array([1, 2, 4, 2, 2, 4, 2, 2, 4, 2])

In [9]:
# E10

# How can you create a normal distribution of 10 numbers, centered on 5?

import numpy as np

array = np.random.normal(5, 1, 10)
array

# Here, the 1 in the center of the .normal() function is the standard deviation

array([4.81829488, 4.53246588, 3.24132913, 4.81329933, 7.25602429,
       3.62730059, 3.52520817, 3.22533064, 3.36854571, 3.60172723])

In [6]:
# E11

# What code would create an array of 10 random numbers between zero and one?

import numpy as np

array = np.random.random(10)
array

array([0.69835659, 0.84902912, 0.0387064 , 0.77954778, 0.46102078,
       0.13172437, 0.205036  , 0.8189816 , 0.43660574, 0.49087579])

In [3]:
# E12

# Consider the code: np.ones(3,5). Does this:
# A) create an array of three arrays containing five elements each or
# B) create an array of five arrays containing three elements each?

# Answer: A. Actually it returns an error if you write it exactly as it says. The first parameter of .ones() is "shape",
# so if you want a 2D array of shape (3,5), you must use the parantheses like this: n.ones((3,5)), otherwise if you write
# np.ones(3,5), it'll think your first parameter is "3" and the second is "5"

import numpy as np

array = np.ones((3,5))
array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [2]:
# E13

# Consider an array named “myarray” that is displayed like this:

# array([[ 1,  2,  3,  4],
#       [ 5,  6,  7,  8],
#       [ 9, 10, 11, 12]])

# What value does the code myarray[1,2] return?
# A) 10
# B) 7.

# Answer: B) 7

import numpy as np

myarray = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
myarray[1,2]

7